### ISSUE TITLE
Host is unreachable

### ISSUE THREAD

**Issue by stigvi** [echoromeo/pynobo#14]
Fikk denne i natt som da viste seg å være "fatal" for pynobo.

2019-10-23 03:27:02 ERROR (Thread-2) [custom_components.nobo_hub.pynobo.nobo] Unhandeled exception: [Errno 113] Host is unreachable
Traceback (most recent call last):
  File "/config/custom_components/nobo_hub/pynobo/nobo.py", line 381, in socket_receive
    resp = self.get_response(True)
  File "/config/custom_components/nobo_hub/pynobo/nobo.py", line 352, in get_response
    response += self.client.recv(bufsize)
OSError: [Errno 113] Host is unreachable

Har endret koden slik at OsError fanges opp istedenfor ConnectionError og ser etterhvert om det blir bedre.

Edit: Ser nå at "Unhandeled exception: [Errno 113] Host is unreachable" forvirret meg. Den er jo håndtert i koden selv om det står "Unhandeled exception" og da nytter det ikke å fange OsError avbrudd.

Skal kikke litt på hvorfor ikke pynobo kommer i gang igjen av seg selv.....

Edit 2: Jeg er trøtt..... Å fange opp OsError er vist veien å gå allikevel

**Comment by echoromeo** [comment]
Det ser veldig likt ut som #9 men det skjedde så sjelden at eg ikkje klarte å reprodusere problemet. I tillegg forsvann problemet med bytte av router.
